// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "JapoTrip",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "JapoTrip",
            targets: ["AppModule"],
            bundleIdentifier: "com.cesc.japotrip",
            teamIdentifier: "43M4NL6S5P",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .asset("AccentColor"),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight(.when(deviceFamilies: [.pad])),
                .landscapeLeft(.when(deviceFamilies: [.pad])),
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            additionalInfoPlistContentFilePath: "AdditionalInfo.plist"
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            resources: [
                .process("Assets.xcassets"),
                .copy("Resources/data.json")
            ]
        )
    ]
)