# -*- coding: utf-8 -*-
"""Descripcions ampliades (v4) — Osaka (reescriptures) i la resta de ciutats."""

REWRITE_B = {
    # ---------------- OSAKA (les descripcions d'una sola línia es reescriuen senceres) ----------------
    "osaka__p2": "Santuari xintoista fundat l'any 949 i dedicat a Sugawara no Michizane (Tenjin), el patró dels estudis, que els d'Osaka anomenen afectuosament «Tenma no Tenjin-san». És l'amfitrió del Tenjin Matsuri de finals de juliol, un dels tres grans festivals del Japó, amb una processó de barques i focs artificials al riu Okawa. El recinte és tranquil i molt local, amb un pati de pruners que floreixen al febrer i parades els dies de festa; queda a l'inici del carrer comercial Tenjinbashi-suji, de manera que es combinen perfectament.",
    "osaka__p3": "Amb 2,6 quilòmetres i unes 600 botigues, és la galeria comercial coberta més llarga del Japó: travessa de sud a nord els barris de Tenma i Tenjinbashi i es recorre en uns 40 minuts sense parar. No és un carrer turístic sinó el mercat quotidià dels veïns: peixateries, botigues de te i ceràmica, farmàcies, sabateries de 1.000 iens, izakaya diminuts i paradetes de takoyaki i croquetes. A l'extrem sud hi ha el santuari Tenmangu i el Museu de la Vida i l'Habitatge d'Osaka, amb la reconstrucció d'un carrer del període Edo a escala real.",
    "osaka__p4": "Illa estreta i allargada entre els rius Dojima i Tosabori, al cor administratiu i cultural d'Osaka. Hi conviuen l'edifici neorenaixentista de l'antic Ajuntament, la Biblioteca Prefectural de Nakanoshima (1904) amb la seva cúpula, l'auditori Central Public Hall de maó vermell, el Museu de Ceràmica Oriental (amb una col·lecció xinesa i coreana de primer nivell), el nou Museu d'Art de Nakanoshima (2022) i un parc amb un roserar de 3.700 rosers que floreixen al maig i a l'octubre. Al vespre els edificis s'il·luminen i el passeig fluvial és ideal per caminar cap a Umeda.",
    "osaka__p5": "Centre comercial de nou plantes al mig d'Umeda, obert el 1998 i orientat al públic jove (moda, videojocs, Sega, botigues de cartes), coronat per una nòria vermella de 106 metres de diàmetre que sobresurt de la teulada. La volta dura uns 15 minuts i des de dalt es veu tot el nord d'Osaka, amb l'Umeda Sky Building i, en dies clars, la badia; és especialment bonica de nit. Sota la nòria, a l'atri, penja una balena vermella gegant de 20 metres.",
    "osaka__p6": "Edifici d'oficines de 16 plantes construït el 1992 al barri de Fukushima, famós arreu del món perquè l'autopista Hanshin (sortida Umeda) el travessa literalment per les plantes 5, 6 i 7. La solució va ser el resultat d'anys de negociació entre la propietat, que tenia dret a construir-hi, i l'autoritat de carreteres, que necessitava el pas: l'autopista no toca l'edifici i les plantes travessades són simplement l'ascensor, que passa de llarg sense aturar-s'hi. No es pot visitar per dins, però es fotografia molt bé des del carrer o des de l'Umeda Sky Building.",
    "osaka__p8": "El gran complex que envolta l'estació JR d'Osaka, reconvertit el 2011 en una ciutat vertical de centres comercials (Lucua, Daimaru, Hankyu, Grand Front), restaurants i terrasses amb jardins a diferents nivells, unides per una gran coberta de vidre sobre les andanes. Al costat de l'estació de Hankyu Umeda, sota el gran magatzem, hi ha la pantalla gegant «Big Man», el punt de trobada per excel·lència dels d'Osaka. La plaça superior Toki no Hiroba, amb el rellotge d'aigua, és un bon lloc per veure el moviment dels trens des de dalt.",
    "osaka__p9": "Cadena nascuda a Osaka el 1945 i convertida en icona local: els butaman són panets de pa al vapor farcits de porc i ceba, que s'elaboren a mà davant del client a cada botiga i es venen calents, amb mostassa. El nom ve del número de telèfon original. A l'estació d'Osaka, a Namba i a totes les grans estacions hi ha parades amb cua constant, sobretot a última hora de la tarda quan la gent torna cap a casa; també fan shumai i gyoza. Un butaman costa poc més de 200 iens i és el berenar més osakenc que hi ha.",
    "osaka__p10": "El negiyaki és una variant de l'okonomiyaki nascuda en aquest restaurant de Juso als anys 60: en lloc de col, la massa és plena de ceba tendra picada i es serveix amb salsa de soja i llimona en lloc de la salsa espessa habitual, de manera que resulta més lleuger i aromàtic. Yamamoto té diversos locals (el més còmode és el de la planta 27 de Lucua a Osaka Station o el de Namba Dining Maison) i el de Juso, l'original, encara és el més autèntic. Cal demanar-lo amb sujiyaki (tendons de vedella) per tastar la versió clàssica.",
    "osaka__p11": "Santuari d'Ebisu, el déu somrient de la pesca, el comerç i la prosperitat, fundat l'any 600 segons la tradició. Els comerciants d'Osaka hi acudeixen en massa durant el Toka Ebisu (9-11 de gener), quan un milió de persones hi passa per comprar branques de bambú decorades amb amulets de la sort. La resta de l'any és tranquil, amb un ambient de barri, i queda molt a prop del Den Den Town i de Shinsekai; també hi ha un gran tambor que es pica per «despertar» Ebisu, que es diu que és una mica sord.",
    "osaka__p12": "Temple budista de la Terra Pura fundat el 1185, conegut per la seva porta d'entrada moderna de formigó i bronze (1997) amb dues estàtues de guardians molt expressives, obra de l'abat escultor. És famós sobretot per les seves «Okotsu Butsu», estàtues de Buda fetes cada deu anys amb les cendres de centenars de milers de fidels, que s'hi porten des de tot el Japó: un culte popular molt arrelat a Osaka. El recinte és al costat del parc Tennoji i del Shitennoji, i té una vista peculiar del gratacel Abeno Harukas darrere de la pagoda.",
    "osaka__p14": "Petit santuari xintoista fundat segons la tradició pel príncep Shotoku al segle VI, com a part del complex de Shitennoji, i dedicat al seu oncle, el príncep Sakurai. Té un gran ginkgo, un estany amb un pont i una atmosfera molt tranquil·la, i és conegut pels «ichigan» o «un desig per vida»: es diu que el santuari concedeix un únic desig important a cada persona. Els cirerers i la floració de tardor són bonics i sol estar buit; és a cinc minuts de la porta sud del Shitennoji.",
    "osaka__p15": "El gran parc del barri de Tennoji, obert el 1909, amb un jardí japonès (Keitakuen, dissenyat per Jihei Ogawa), el Museu Municipal d'Art en un edifici de 1936, el zoo de Tennoji (un dels més antics del Japó, amb koales i un espai de savana) i una gran esplanada de gespa anomenada «Ten-shiba» amb cafeteries, terrasses i vistes al gratacel Abeno Harukas i a la torre Tsutenkaku. És un bon lloc per descansar entre Shinsekai i Abeno, i els caps de setmana s'hi fan mercats i activitats.",
    "osaka__p18": "Kushikatsu són broquetes de carn, verdura, marisc o formatge arrebossades amb pa ratllat fi i fregides, que es serveixen amb una salsa fosca compartida a taula: la regla d'or, escrita a cada local, és no sucar-hi mai dues vegades (es fa servir la col crua per posar-hi salsa si cal). Daruma és el restaurant que va inventar el plat el 1929 a Shinsekai, on el local original, amb la cara enfadada del cuiner al rètol, encara està obert i sovint té cua; hi ha sucursals a Dotonbori i Namba. Una broqueta costa entre 100 i 300 iens.",
    "osaka__p19": "Gran complex de banys de vuit plantes al costat de Shinsekai, obert el 1997, amb zones d'onsen tematitzades per continents: l'«europea» (banys romans, grecs, finlandesos, una gruta blava) i l'«asiàtica» (japonès a l'aire lliure, persa, balinès), que s'intercanvien entre homes i dones cada mes. Té també saunes de pedra, piscines amb tobogans obertes tot l'any i una zona de descans amb restaurants; es pot passar-hi una tarda sencera. Com a tots els onsen, els tatuatges grans poden ser un problema; l'entrada és per hores o per dia.",
    "osaka__p21": "L'únic tramvia que queda a Osaka: dues línies (Hankai i Uemachi) que van des de Tennoji-ekimae i Ebisucho fins a Sumiyoshi Taisha i, més enllà, fins a Sakai, amb vagons antics de colors que circulen pel mig del carrer entre cases baixes i botigues de barri. El trajecte de Tennoji a Sumiyoshi dura uns 20 minuts i és la manera més bonica d'arribar al santuari; el preu és fix (poc més de 200 iens) i es paga en baixar, també amb Icoca/Suica. És l'Osaka de veïns, lluny dels neons.",
    "osaka__p23": "Santuari xintoista del barri de Namba famós per la seva Ema-den: una escenari en forma de cap de lleó gegant de 12 metres d'alçada, amb la boca oberta i els ulls brillants, que segons la tradició s'empassa els mals esperits i porta sort en els negocis i els estudis. El santuari actual és de 1974 (l'anterior va cremar a la guerra) i queda a cinc minuts de Namba Parks i Dotonbori, en un carrer residencial tranquil. Al gener s'hi fa un festival d'estirar la corda (tsunahiki) amb una corda en forma de serp.",
    "osaka__p24": "Centre comercial obert el 2003 sobre l'antic estadi de beisbol de Namba, dissenyat per l'arquitecte Jon Jerde com un canó natural: façanes corbes de pedra en tons ocres, un carrer interior que s'enfila entre les plantes i, a les terrasses, un jardí de 11.500 m² amb arbres, horts, un petit amfiteatre i racons per seure, que puja escalonadament fins a la planta 9. Hi ha botigues de moda, un cinema i una planta de restaurants; és un lloc excel·lent per descansar del bullici de Namba i fer fotos al capvespre.",
    "osaka__p25": "L'Akihabara d'Osaka: un barri d'electrònica, manga, anime, videojocs, figures, cartes i maid cafés al voltant de Sakaisuji, just al sud de Namba. Hi ha les grans cadenes (Animate, Mandarake, Super Potato per a retro-gaming, Joshin Super Kids Land per a maquetes) i molts edificis petits amb botigues especialitzades a cada planta, així com Ota Road, el carrer dels aficionats. La zona és menys atapeïda i una mica més barata que Akihabara, i molt a prop hi ha el carrer d'estris de cuina Doguyasuji.",
    "osaka__p26": "Carrer cobert de 150 metres, a tocar de Namba, dedicat exclusivament als estris de cuina professionals des de fa més de cent anys: bols de laca, ganivets, planxes per a takoyaki, olles de ramen, fanalets de paper, cartells de restaurant i els menjars de plàstic dels aparadors. És l'equivalent osakenc de Kappabashi a Tòquio però més compacte, i els preus solen ser més bons. Molts turistes hi compren un motlle de takoyaki o un ganivet; hi ha una botiga on es poden fer tallers de sampuru (menjar de plàstic).",
    "osaka__p28": "Petit temple budista del segle XVII amagat en un carreró a un pas de Dotonbori, conegut per l'estàtua de Fudo Myo-o (Mizukake Fudo) que està completament coberta de molsa verda: els fidels hi tiren aigua amb un cullerot mentre demanen un desig, i després de segles de ruixades la molsa l'ha recobert del tot. Hi ha fanalets encesos i sempre una petita cua de gent, tant de dia com de nit, i és una parada obligada per veure la cara més tradicional d'Osaka al bell mig de la zona més sorollosa.",
    "osaka__p29": "Carreró empedrat de només 80 metres, al darrere del temple Hozenji, amb una seixantena de petits restaurants i bars tradicionals (kappo, okonomiyaki, kushikatsu, yakitori, bars de sake) en cases baixes de fusta amb fanalets, que ha sobreviscut als incendis i a la remodelació de la zona. És l'ambient més «Osaka antiga» que es pot trobar al centre, i de nit és preciós; alguns locals són cars i selectes, però n'hi ha de senzills, i el mateix carrer és famós per la novel·la «Meoto Zenzai», amb la botiga de dolços del mateix nom.",
    "osaka__p30": "A la zona de Hozenji i Dotonbori hi ha diversos restaurants especialitzats en wagyu de Matsusaka, una de les tres grans vedelles del Japó (amb Kobe i Omi), criada a la prefectura de Mie i famosa pel greix infiltrat que es fon a la boca. Es pot tastar en format yakiniku (a la brasa a la taula), sukiyaki o com a bistec a la planxa; els menús de migdia són molt més assequibles que els de sopar. Convé reservar per la nit, i preguntar si el wagyu és certificat de Matsusaka (amb el segell oficial).",
    "osaka__p31": "Galeria comercial coberta que va del sud del pont Ebisubashi (Dotonbori) fins a Namba, plena de botigues de moda, drogueries (Don Quijote, Matsumoto Kiyoshi), botigues de dolços, pastisseries com Rikuro Ojisan i sempre plena de gent. És la continuació natural de Shinsaibashi-suji cap al sud i el camí més directe per anar caminant de Dotonbori a Namba Parks; sota el carrer hi ha també la galeria subterrània Namba Walk.",
    "osaka__p32": "Pastisseria d'Osaka famosa pel seu pastís de formatge «tremolós», de 18 cm i molt esponjós, fet amb formatge crema danès i panses al fons, que surt del forn cada pocs minuts amb el segell del cuiner somrient marcat a sobre. La botiga principal és a Namba (Ebisubashi-suji) i sempre hi ha cua, però avança ràpid; costa menys de 1.000 iens sencer i es menja millor calent, tot i que també és bo fred de la nevera l'endemà. És un dels souvenirs comestibles més populars d'Osaka.",
    "osaka__p34": "El rètol lluminós de l'atleta de Glico creuant la meta amb els braços alçats presideix el canal de Dotonbori des de 1935 (la versió actual, amb LEDs, és de 2014). És la foto icònica d'Osaka i el lloc més ple de la ciutat: la millor perspectiva és des del pont Ebisubashi, on tothom s'atura per imitar la postura. Al voltant hi ha els altres rètols famosos (el cranc mecànic de Kani Doraku, el drac de Kinryu Ramen, el pop gegant) i la passarel·la del canal, des d'on surten els vaixells de Tombori River Cruise.",
    "osaka__p35": "El «Kuidaore Taro» és un ninot mecànic vestit de pallasso, amb ulleres i un tambor, que va presidir l'entrada del restaurant Cui-daore de Dotonbori des de 1950 fins que va tancar el 2008, i ara es troba a l'entrada de l'edifici Nakaza Cui-daore, on tothom es fa la foto. El nom ve de la dita «Kyoto s'arruïna vestint-se, Osaka s'arruïna menjant» (kuidaore), el lema gastronòmic de la ciutat. Al mateix edifici hi ha restaurants i botigues de souvenirs de Taro.",
    "osaka__p36": "Cadena d'okonomiyaki fundada el 1967 al barri coreà de Tsuruhashi, que ha crescut fins a tenir locals a tot el Japó. L'okonomiyaki (la «truita» d'Osaka amb col, ou, massa i el que es vulgui a sobre: porc, gambes, calamar, formatge) es cuina a la planxa de la taula i s'acaba amb salsa dolça, maionesa, flocs de bonítol i alga en pols. Fugetsu és una opció fiable i amb carta en anglès; hi ha locals a Dotonbori, Umeda i Namba, i el modan-yaki (amb fideus yakisoba dins) és la seva especialitat.",
    "osaka__p37": "Restaurant d'okonomiyaki obert el 1965 a Namba, considerat per molts el millor de la ciutat: la massa és més lleugera que en altres llocs, l'ou es barreja d'una manera especial i la varietat «Ajinoya-yaki», amb porc, calamar, gambes, carn picada i konjac, és el plat estrella. És un local petit, amb la planxa a la barra i cues d'entre 30 i 60 minuts a les hores punta; val la pena anar-hi a mitja tarda. Té estrella Bib Gourmand de Michelin i un segon local a prop.",
    "osaka__p39": "L'avinguda principal d'Osaka, de quatre quilòmetres entre Umeda i Namba, flanquejada per files de ginkgos que es tornen daurats al novembre i il·luminats per Nadal. Hi ha les botigues de luxe (Louis Vuitton amb façana de vela, Chanel, Hermès), els grans magatzems Daimaru, edificis històrics com el Gas Building i el Museu Semba de l'Arquitectura, i al tram de Shinsaibashi, el pont que dona nom al barri. Els diumenges a la tarda de vegades es tanca al trànsit per a esdeveniments.",
    "osaka__p43": "Carreró gastronòmic amb aire retro dins el centre comercial Tempozan Marketplace, al port d'Osaka, tematitzat com un carrer dels anys 60 (era Showa) amb façanes antigues, rètols de neó i cartells d'època, i una vintena de parades de menjar típic d'Osaka: takoyaki, okonomiyaki, kushikatsu, ramen i dolços. És còmode per dinar abans o després de l'aquari Kaiyukan i de la nòria, sobretot amb pluja, i els preus són raonables.",
    "osaka__p45": "El Takoyaki Park («Takopa») és un espai de la quarta planta de l'Universal Citywalk, el centre comercial a l'entrada dels Universal Studios Japan, que reuneix sis parades de takoyaki famoses d'Osaka (Aizuya, Kukuru, Juhachiban...) sota un mateix sostre, amb taules compartides i un petit museu. No cal entrada al parc per accedir-hi, de manera que és una manera d'aprofitar el trajecte fins a Universal City sense entrar a l'atracció. També hi ha els takoyaki en rul·lo i versions amb formatge.",
    "osaka__p48": "Temple budista de muntanya al nord d'Osaka (Minoo), fundat el 727 i conegut com el «temple de la victòria» (katsu = guanyar): els fidels hi compren un daruma (ninot de la determinació) i n'hi pinten un ull en demanar un objectiu; quan s'aconsegueix, el pinten de l'altre i el tornen al temple, de manera que tot el recinte està literalment cobert de milers de daruma vermells posats a les baranes, les llanternes i les estàtues. El jardí, amb un estany i una pagoda, és preciós a la tardor, i s'hi arriba en autobús o taxi des de Minoo o Senri-Chuo.",
    "osaka__p49": "Ciutat al sud d'Osaka, a mitja hora en tren, que va ser un gran port comercial i on va néixer la cerimònia del te de Sen no Rikyu. Té tres visites destacades: el Mozu Kofun, el gran túmul funerari de l'emperador Nintoku (segle V, en forma de forat de pany i Patrimoni de la Humanitat), que es veu millor des del mirador gratuït de la planta 21 de l'Ajuntament; els tallers de ganivets, que produeixen la major part dels ganivets professionals del Japó (amb museu i botiga al centre de Sakai Hamono); i el museu Sakai Plaza de Rikyu i Akiko Yosano. El tramvia Hankai hi arriba des de Tennoji.",
    "osaka__p50": "Museu dedicat a Osamu Tezuka, el creador d'Astro Boy, Kimba el lleó blanc i Black Jack, considerat el pare del manga i de l'anime modern, situat a Takarazuka (on va créixer), a mitja hora en tren des d'Umeda per la línia Hankyu. Té una reconstrucció del seu estudi, originals, un cinema amb curts d'animació i un taller on es pot animar; l'edifici, amb forma de castell de vidre, té les mans de bronze d'Astro Boy a l'entrada. Es pot combinar amb el teatre de la Takarazuka Revue, al mateix carrer.",
    "osaka__p51": "Museu a Ikeda, la ciutat on Momofuku Ando va inventar el ramen instantani el 1958, situat a mitja hora en tren (línia Hankyu Takarazuka) des d'Umeda. L'entrada és gratuïta i el més popular és el taller «My Cup Noodles Factory», on cada visitant dissenya el seu propi envàs, tria el brou i quatre ingredients i se l'emporta segellat (500 iens); també hi ha una rèplica de la cabana on es va crear el primer Chicken Ramen i un túnel amb tots els envasos de la història. Cal reservar per als tallers de fer fideus a mà.",
}

EXTEND_B = {
    # ---------------- NIKKO ----------------
    "nikko__rinnoji": " Fundat el 766 per Shodo Shonin, el monjo que va obrir Nikko a la religió, és el temple més important de la regió i forma part del Patrimoni de la Humanitat conjunt amb Toshogu i Futarasan. Al costat del Sanbutsudo hi ha el jardí Shoyo-en, un jardí d'estany a l'estil dels d'Edo molt bonic amb els colors de tardor, i un tresor amb objectes dels Tokugawa. L'entrada combinada amb Taiyuin surt a compte.",
    "nikko__kanmangafuchi": " Els Jizo, coberts de gorros i bavalls vermells, es coneixen també com a «Bake Jizo» (Jizo fantasma), perquè segons la llegenda ningú no aconsegueix comptar-ne el mateix nombre a l'anada i a la tornada. El passeig comença just després del pont Shinkyo, a uns 20 minuts a peu dels temples seguint el riu, i es fa en mitja hora, amb el so de l'aigua que baixa entre roques volcàniques.",
    "nikko__botanical-garden": " Depèn de la Universitat de Tòquio i va ser fundat el 1902 per estudiar les plantes alpines; té 10 hectàrees amb estanys, un tram de riu i més de 2.000 espècies, amb un moment especialment bonic a finals d'abril-maig (azalees, rododendres) i a l'octubre-novembre pels colors de les arces. És a tocar de la vil·la Tamozawa i tanca els dilluns i a l'hivern.",
    "nikko__tamozawa": " Amb 106 habitacions, és la residència de fusta més gran del Japó que es conserva del període Meiji, i parts de l'edifici provenen d'una residència dels Tokugawa a Edo. Es visita descalç seguint els passadissos de tatami, amb els sostres, els papers de paret i els vidres d'època intactes, i el jardí és preciós a la tardor; queda a 15 minuts a peu del Shinkyo i tanca els dimarts.",
    "nikko__chuzenji": " El llac és a 1.269 metres d'altitud, al peu del mont Nantai, i s'hi arriba en uns 50 minuts d'autobús des de l'estació de Nikko per la carretera de corbes Irohazaka (48 corbes, amb el mirador Akechidaira i el seu telefèric). Les cascades Kegon, de 97 metres, són a la sortida del llac i tenen un ascensor fins a una plataforma inferior; a la riba hi ha les vil·les d'ambaixades italiana i britànica, visitables, i vaixells turístics. Els colors de tardor arriben abans aquí que al nucli (mitjan octubre).",
    "nikko__yumoto-onsen": " És a 1.500 metres d'altitud, a la vora del llac Yunoko, al final de la carretera que puja des de Chuzenji passant per les cascades Ryuzu i l'altiplà de Senjogahara (amb un sender de passarel·les de fusta molt recomanable a la tardor). L'aigua és sulfurosa i lletosa, i s'hi pot fer un bany de dia a diversos ryokan o al bany públic; també hi ha una font on l'aigua brolla directament del sòl (Yunodaira).",
    "nikko__kinugawa-onsen": " Kinugawa, a 40 minuts en tren Tobu des de Nikko, és una vall de grans hotels i ryokan a la vora d'un riu encaixonat, amb barques de descens ràpid (Kinugawa Line Kudari), un parc de miniatures del món (Tobu World Square) i el parc temàtic del període Edo (Edo Wonderland). Kawamata, més amunt, és un poble d'onsen molt petit i tranquil en plena natura, amb el pont penjant Setoai-kyo sobre un congost.",

    # ---------------- KAMAKURA ----------------
    "kamakura__kenchoji": " Fundat el 1253 pel mestre xinès Rankei Doryu, és el temple zen més antic del Japó que funciona com a tal i encara té monjos en formació. La porta Sanmon, la campana (tresor nacional) i els vells arbres de ginebre plantats pel fundador són a l'entrada; al fons, l'escalinata puja fins al santuari Hansobo, amb estàtues de tengu i un mirador des d'on, en dies clars, es veu el mont Fuji. D'aquí surt el sender Ten-en cap a Zuisen-ji.",
    "kamakura__engakuji": " Fundat el 1282 per commemorar els caiguts a les invasions mongoles, és el segon dels cinc grans temples i el recinte s'enfila per una vall de cedres amb més d'una desena de subtemples. Destaquen el Shariden, un dels edificis més antics de Kamakura (tresor nacional), la campana gegant Ogane al capdamunt d'una escala amb una casa de te, i els jardins de tardor; s'hi pot participar en sessions de meditació zazen obertes al públic.",
    "kamakura__jochiji": " És el quart dels cinc grans temples, fundat el 1281, i és molt petit i íntim: un pou (una de les deu aigües famoses de Kamakura), una campana sobre la porta, el saló amb tres budes del passat, present i futur, i un jardí de bambú amb una petita cova i una estàtua de Hotei, el déu somrient a qui es frega la panxa per tenir sort. D'aquí comença el sender Daibutsu cap al Gran Buda (uns 60-90 minuts pel bosc).",
    "kamakura__jomyoji": " Fundat el 1188, és a la zona est de Kamakura, a prop de Hokoku-ji, i té una casa de te (Kisen-an) on es pot prendre matcha mirant el jardí sec; al turó del darrere hi ha un restaurant d'estil occidental en una vil·la antiga, i el camí que puja darrere el temple porta a un petit santuari amb vistes. És tranquil i el visiten pocs turistes.",
    "kamakura__zuisenji": " Fundat el 1327 per Muso Soseki, el gran dissenyador de jardins, conserva darrere el saló principal el seu jardí de roca zen excavat directament a la paret de pedra, amb una cova i un estany, únic a Kamakura. La vall és coneguda com «el temple de les flors» perquè té flor tot l'any (narcisos, pruners, azalees, hortènsies). És l'inici del sender Ten-en, que puja fins al Kencho-ji.",
    "kamakura__meigetsuin": " Fora de la temporada d'hortènsies el temple és molt tranquil i té altres atractius: la finestra rodona del saló principal que emmarca el jardí del darrere (obert només a la primavera i la tardor), les tombes excavades a la roca (yagura), un jardí sec i esquirols i conills. És a cinc minuts de l'estació de Kita-Kamakura i a la tardor les arces del jardí interior són precioses.",
    "kamakura__egara-tenjinsha": " Fundat el 1104, és un dels tres grans santuaris de Tenjin del Japó, juntament amb Dazaifu i Kitano de Kyoto, i té un ginkgo de 900 anys i pruners que floreixen al febrer. Un monument dedicat als dibuixants de manga, amb pedres gravades amb les mans de Tezuka i altres autors, recorda el veí Yokoyama Ryuichi. És a mig camí entre el Hachimangu i Kamakura-gu, en un turó.",
    "kamakura__sugimotodera": " Fundat el 734, més de quatre segles abans de la fundació del shogunat, és el temple número 1 de la ruta de pelegrinatge Bando de 33 temples de Kannon i conserva tres estàtues de Kannon d'onze cares. L'escalinata de molsa ja no es pot trepitjar (s'hi puja per una de lateral) i a dalt hi ha el saló amb teulada de palla ple de banderoles blanques; és a dos minuts de Hokoku-ji.",
    "kamakura__wakare-enoshima": " El port de Wakaenoshima es va construir el 1232 i és el port artificial més antic que es conserva al Japó, declarat lloc històric; les roques que apareixen amb la marea baixa són les restes del dic. Es veu millor a l'extrem est de la platja de Zaimokuza, prop del temple Kōmyō-ji, i a l'estiu la zona té bars de platja; convé consultar les hores de marea.",

    # ---------------- HAKONE ----------------
    "hakone__shogenji": " És un temple de l'escola Soto zen amb un jardí petit i una porta de fusta antiga, situat a la vora del carrer principal pujant cap als ryokan, i és una bona excusa per allunyar-se una mica de les botigues de souvenirs; a la zona hi ha també el santuari Kumano i l'onsen públic Kappa Tengoku amb banys a l'aire lliure.",
    "hakone__pont-hayakawa": " La parada més coneguda és a l'alçada de Tonosawa i el pont ferroviari Dearai-gawa, on el tren Hakone Tozan, el més antic tren de muntanya del Japó (1919), fa ziga-zagues amb tres canvis de sentit per salvar el desnivell; al juny les vies estan flanquejades per milers d'hortènsies i s'organitzen trens nocturns il·luminats. Els aficionats s'hi apleguen a primera hora del matí.",
    "hakone__hakone-daitengu": " Els tengu, amb el nas llarg vermell i les ales, són els guardians de les muntanyes i el santuari està ple d'estàtues i màscares seves entre centenars de fanalets; s'hi arriba en uns 10-15 minuts en autobús o taxi des de Hakone-Yumoto per la carretera del riu Sukumo, i hi ha una petita zona de camí i cascada al darrere.",
    "hakone__open-air-museum": " Obert el 1969, té més de 120 escultures en 70.000 m² de gespa, amb obres monumentals de Rodin, Bourdelle, Niki de Saint Phalle i Taro Okamoto, el Pavelló Picasso amb més de 300 obres (ceràmica sobretot), la torre de vitralls «Simfonia» a la qual es pot pujar per una escala de cargol i un bany de peus termal per descansar mirant les muntanyes. Cal reservar-hi almenys dues hores; és a l'estació de Chokoku-no-Mori del tren Tozan.",
    "hakone__hakone-art-museum": " Fundat el 1952 per Mokichi Okada, és el museu més antic de Hakone i té ceràmica japonesa des del període Jomon fins a l'era Edo; el jardí Shinsen-kyo, amb 130 espècies de molsa, més de 200 arces i un camí de pedra, és espectacular a partir de mitjan novembre i està considerat un lloc de bellesa escènica nacional. És a la parada Koen-kami del funicular de Gora, al costat del parc de Gora.",
    "hakone__pola-museum": " Obert el 2002, l'edifici de vidre i acer està semienterrat al bosc de fajos de Sengokuhara perquè no sobresurti dels arbres, i té un passeig de bosc exterior amb escultures. La col·lecció d'impressionistes és una de les millors d'Àsia i s'hi fan exposicions temporals que combinen art japonès i occidental; té restaurant i cafeteria amb vistes al bosc, i s'hi arriba amb l'autobús des de Gora (Togendai) o des de Sengokuhara.",
    "hakone__komagatake": " El telefèric surt de Hakone-en (a la riba est del llac) i puja en set minuts fins a 1.327 metres; a dalt hi ha una gran esplanada d'herba, un observatori i el santuari Motomiya, que va ser el lloc original de culte de la muntanya abans que es construís el gran santuari de Hakone a la vora del llac. Amb bon temps es veuen el Fuji, el llac Ashi sencer i, cap a l'altre costat, la badia de Sagami i la península d'Izu.",
    "hakone__narukawa-museum": " Fundat el 1988, té més de 4.000 obres d'artistes moderns de nihonga com Yamamoto Kyujin i Hirayama Ikuo, i el seu saló de vidre panoràmic dona directament sobre el gran torii vermell del santuari de Hakone i el llac: amb bon temps, el Fuji apareix al fons. Hi ha una cafeteria amb la mateixa vista i el museu és a la vora del moll de Moto-Hakone dels vaixells pirata.",
    "hakone__odawara-castle": " El castell original va ser la fortalesa del clan Hojo, que va dominar la regió de Kanto fins que Toyotomi Hideyoshi el va assetjar el 1590; la torre actual es va reconstruir el 1960 i té un museu d'armadures i un mirador al capdamunt amb vistes al mar i a Hakone. El parc té cirerers i un petit museu de samurais on es pot provar armadura; és a 10 minuts a peu de l'estació d'Odawara, la porta del Tozan i del Romancecar.",

    # ---------------- NARA ----------------
    "nara__nara-museum": " Va obrir el 1895 i té dos edificis: l'original, d'estil occidental de l'era Meiji, i el modern, unit per un passadís subterrani amb la col·lecció de bronzes xinesos. Cada any, a finals d'octubre i principis de novembre, acull l'exposició del Shosoin, els tresors del segle VIII del Todai-ji, una de les cites culturals més importants del Japó; la resta de l'any té una col·lecció d'escultura budista excel·lent. És dins del parc de Nara, entre els cérvols.",

    # ---------------- WAKAYAMA ----------------
    "wakayama__daimonzaka": " La pujada fa uns 600 metres i 267 esglaons de llambordes, i comença al pont Furiganebashi vora dos cedres gegants de 800 anys anomenats «els cònjuges»; a mig camí hi havia una gran porta (daimon) que dona nom al camí. Es triga uns 20-30 minuts fins a la base del santuari, i s'hi arriba en autobús des de l'estació de Kii-Katsuura (parada Daimonzaka); és la manera més bonica d'arribar a Nachi.",
    "wakayama__kii-katsuura": " El mercat de tonyina, a primera hora del matí, es pot veure des d'una galeria elevada; al port hi ha restaurants amb sashimi i donburi de tonyina fresca a preus molt raonables. Els grans hotels-onsen com el Hotel Urashima (amb la cova termal Bokido oberta al mar) i el Nakanoshima s'arriben amb vaixells propis des del moll. El tren Kuroshio hi arriba des de Shin-Osaka en unes quatre hores.",
    "wakayama__kumano-hayatama-taisha": " El santuari actual, de color vermell intens, és a la ciutat de Shingu, a 20 minuts en tren de Kii-Katsuura; al recinte hi ha un arbre nagi de 1.000 anys (el més antic del Japó) i el santuari original, Kamikura-jinja, és dalt d'un turó al qual es puja per 538 esglaons de pedra irregulars fins a una roca sagrada gegant (Gotobiki-iwa) amb vistes al mar. Els tres santuaris es poden visitar en un dia amb autobús i tren des de Katsuura.",

    # ---------------- HIROSHIMA ----------------
    "hiroshima__hondori": " El carrer fa uns 600 metres, des del Parc de la Pau fins a l'avinguda Chuo-dori, i és el lloc més fàcil per sopar o comprar a Hiroshima; hi ha grans magatzems, la botiga de souvenirs de Hiroshima, drogueries i moltes cadenes de restaurants. Als carrers paral·lels (Nagarekawa) hi ha la zona de bars i izakaya de la ciutat, i els carrerons perpendiculars amaguen bons locals d'okonomiyaki i d'ostres a la brasa.",
    "hiroshima__aioi-dori": " L'avinguda ressegueix la línia nord del Parc de la Pau, i el pont Aioi, amb la seva forma de T única, era el punt de mira de la bomba atòmica; el tramvia hi circula tot el dia i des de les seves voreres es té una de les millors perspectives de la Cúpula. Hi ha també edificis com el Bank de Hiroshima, el Museu d'Art Contemporani i, a l'extrem est, el centre de la ciutat.",
    "hiroshima__orizuru-tower": " Oberta el 2016 en un edifici d'oficines de 13 plantes, el mirador de fusta a cel obert Hiroshima Hills permet veure la Cúpula des de dalt, tot el Parc de la Pau, el riu i, en dies clars, Miyajima; a la planta 12 hi ha la «Paret Orizuru», on es pot plegar una grua de paper i llançar-la des de dalt perquè s'acumuli a la façana de vidre. Es baixa per un tobogan en espiral i a la planta baixa hi ha una bona botiga de productes locals.",
    "hiroshima__museus-art": " El Museu d'Art de Hiroshima, al parc del castell, té una col·lecció d'impressionistes francesos (Monet, Renoir, Van Gogh, Picasso) en un edifici circular; el Prefectural, al costat del Shukkei-en, té Dalí i art japonès modern, i es pot comprar entrada combinada amb el jardí; i el Museu d'Art Contemporani (MOCA), al parc Hijiyama, redissenyat per Kisho Kurokawa i reobert el 2023, té vistes sobre la ciutat.",
    "hiroshima__mazda-museum": " El museu, reformat el 2022, és dins la immensa fàbrica de Mazda a Fuchu (a cinc minuts en tren de l'estació de Hiroshima, parada Mukainada), i la visita d'una hora i mitja inclou la història de la marca, els motors rotatius, el cotxe guanyador de Le Mans 1991 i, el més interessant, un tram real de la línia de muntatge on es veuen els cotxes en construcció. Les reserves s'obren en línia amb setmanes d'antelació i les visites en anglès són a les 10 h.",
    "hiroshima__iwakuni": " El pont es travessa amb una petita entrada i des de l'altra banda es pot pujar amb telefèric al castell d'Iwakuni, reconstruït el 1962, amb vistes al riu Nishiki i al mar interior de Seto; al parc Kikko hi ha també un santuari amb serps blanques sagrades, úniques d'aquí. Es tarda uns 50 minuts des de Hiroshima en tren local fins a Iwakuni més un autobús de 20 minuts, o bé s'agafa el Shinkansen fins a Shin-Iwakuni. Es pot combinar amb Miyajima, que queda a mig camí.",
    "hiroshima__kurashiki": " El barri de Bikan té també el Museu d'Art Ohara, el primer museu d'art occidental del Japó (1930) amb El Greco, Monet i Gauguin; l'Ivy Square, una antiga filatura coberta d'heura amb hotel i tallers; i moltes botigues d'artesania i cafeteries en antics magatzems (kura). Es tarda uns 40 minuts des d'Hiroshima en Shinkansen fins a Okayama més 15 minuts de tren local; és una bona parada en el trajecte cap a Osaka o Himeji.",

    # ---------------- HIMEJI ----------------
    "himeji__museu-art-himeji": " L'edifici és un antic magatzem militar de maó vermell de 1905, dissenyat pel mateix estil que la Tokyo Station, i alberga art belga i francès dels segles XIX-XX (Delvaux, Magritte) i pintors locals; el jardí d'escultures és d'accés lliure i queda al nord-est del castell, a cinc minuts a peu de la porta principal, amb el castell just al darrere del museu, una de les fotos més boniques de la ciutat.",
    "himeji__museu-historia-hyogo": " L'edifici és obra de Kenzo Tange i té una maqueta a gran escala del castell tal com era al període Edo, maquetes d'altres castells japonesos, i una sala per provar-se armadures i quimonos gratuïtament (unes quantes vegades al dia). El museu és al parc Shirotopia, on abans hi havia les residències dels samurais, a la zona més tranquil·la del recinte del castell.",
    "himeji__mont-shosha-engyoji": " El complex té tres grans salons de fusta (Maniden, aixecat sobre pilars a la vessant; Daikodo, Jikido i Jogyodo, tres edificis enormes al voltant d'una esplanada) i camins de bosc amb estàtues; s'hi pot dormir i tastar el menjar vegetarià dels monjos. L'autobús número 8 des de l'estació de Himeji arriba al telefèric en 30 minuts, i el bitllet combinat d'autobús i telefèric surt a compte. A la tardor és un dels llocs amb més color de la zona.",
}
